-- // Adding Data to Member Table

INSERT INTO MEMBER_DETAILS VALUES(100, 'MEMBER_FN_1', 'MEMBER_LN_1', 'MEMBER_1@MAILINATOR.COM', 'N');
INSERT INTO MEMBER_DETAILS VALUES(200, 'MEMBER_FN_2', 'MEMBER_LN_2', 'MEMBER_2@MAILINATOR.COM', 'N');
INSERT INTO MEMBER_DETAILS VALUES(300, 'MEMBER_FN_3', 'MEMBER_LN_3', 'MEMBER_3@MAILINATOR.COM', 'N');
INSERT INTO MEMBER_DETAILS VALUES(400, 'MEMBER_FN_4', 'MEMBER_LN_4', 'MEMBER_4@MAILINATOR.COM', 'N');
INSERT INTO MEMBER_DETAILS VALUES(500, 'MEMBER_FN_5', 'MEMBER_LN_5', 'MEMBER_5@MAILINATOR.COM', 'N');


-- //@UNDO
-- SQL to undo the change goes here.

DELETE FROM MEMBER_DETAILS WHERE MEMBER_ID IN (100, 200, 300, 400, 500);